# Generated by Django 4.0.6 on 2022-08-21 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Libro',
            new_name='Sucursal',
        ),
    ]
