# Generated by Django 4.0.6 on 2022-08-19 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=30)),
                ('apellido', models.TextField(max_length=30)),
                ('dni', models.IntegerField()),
                ('direccion', models.TextField(max_length=50)),
                ('tipo_cliente', models.TextField(max_length=20)),
            ],
        ),
    ]
