# Generated by Django 4.0.6 on 2022-08-19 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomero_tarjeta', models.IntegerField()),
                ('cvv', models.IntegerField()),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateTimeField()),
                ('tipo_tarjeta', models.TextField(max_length=20)),
                ('marca_tarjeta', models.TextField(max_length=20)),
                ('account_id', models.IntegerField()),
                ('customer_id', models.IntegerField()),
            ],
        ),
    ]
