# Generated by Django 4.0.6 on 2022-08-19 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_tarjetas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarjeta',
            old_name='nomero_tarjeta',
            new_name='numero_tarjeta',
        ),
    ]
