# Generated by Django 4.0.6 on 2022-08-22 17:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_total', models.FloatField(default=0)),
                ('loanType', models.TextField(default='Personales', max_length=40)),
                ('loan_month', models.IntegerField(default=1)),
                ('id_cliente', models.IntegerField(default=0)),
                ('loan_approved_date', models.DateField(verbose_name=datetime.datetime(2022, 8, 22, 17, 21, 0, 33397, tzinfo=utc))),
            ],
            options={
                'verbose_name': 'Prestamo',
                'verbose_name_plural': 'Prestamos',
                'ordering': ('-loan_approved_date',),
            },
        ),
    ]
