# Generated by Django 4.0.6 on 2022-08-22 17:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_alter_prestamo_loan_approved_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestamo',
            options={'ordering': ('-created_at',), 'verbose_name': 'Prestamo', 'verbose_name_plural': 'Prestamos'},
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='loan_approved_date',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
